### ISSUE TITLE
Support for multiple tuplets from one command

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/python-ly#14]
From the LilyPond documentation:

>Entering several tuplets using only one \tuplet command

>The property tupletSpannerDuration sets how long each of the tuplets contained within the brackets after \tuplet should last. Many consecutive tuplets can then be placed within a single \tuplet expression, thus saving typing.

>There are several ways to set tupletSpannerDuration. The command \tupletSpan sets it to a given duration, and clears it when instead of a duration \default is specified. Another way is to use an optional argument with \tuplet.

This should of course ultimately be supported by the musicXML export.

The tricky part is knowing where to end the different tuplets only from the `tupletSpannerDuration` property. You have to calculate the durations inside the tuplets.

**Comment by PeterBjuhr** [comment]
@wbsoft is there any function that returns the duration as a base/scaling tuple from a duration token? It would be nice to have the `tupletSpannerDuration` in that format when doing the calculation.

**Comment by wbsoft** [comment]
Do you mean that you want to read the value of the duration in the `\tuplet` command or the argument to a `tupletSpannerDuration` assignment?

**Comment by PeterBjuhr** [comment]
What I've tested so far is when you set the property in the `\tuplet` command. But I don't know if it makes any difference. If it is a `SchemeItem` I have to parse it differently of course.

**Comment by PeterBjuhr** [comment]
As a side note, this...

```lilypond
\tupletSpan 4
```

creates an unpitched duration:

```
 <UserCommand u'\\tupletSpan'>
      <Unpitched>
        <Duration u'4'>
```

**Comment by PeterBjuhr** [comment]
Let's say that the `tupletSpannerDuration` is set in such a way that we end up with a duration element in the tree. And let's say that the duration is `4.`. 

My idea is then to convert this to a fraction '3/8'. And by adding the (duration) fractions in the tuplet see when the tuplet spanner duration gets reached.

In `ly.music.read` duration (or length) tokens are converted to base/scaling fractions (or is it somewhere else?), but I haven't found any usable function for this conversion.

**Comment by wbsoft** [comment]
In `ly.duration` there are functions to convert durations to fractions, e.g.:
```python
>>> import ly.duration
>>> ly.duration.base_scaling_string('4.*3/4')
(Fraction(3, 8), Fraction(3, 4))
```
there is also `base_scaling()` that accepts a list of tokens. This is used in `ly.music.read`, in `add_duration()` where the item that has a Duration child, also gets the duration as a base_scaling tuple in the `duration` attribute.

**Comment by wbsoft** [comment]
To understand the argument of the `\set tupletSpannerDuration = #(ly:make-moment 1 4)` construct, we need indeed to parse a scheme construct. To that end, in 16e73fc6b2860e7bf7566b615bb9eb94c5974bce I added a crude function that can read a simple `#(ly:make-moment 1 4)` expression.

**Comment by PeterBjuhr** [comment]
Thanks a lot!
