### ISSUE TITLE
[ly.music] drum notes are invisible

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/python-ly#15]
In the document tree, notes entered in drum mode is shown only if they have a duration.

Take this example:

````lilypond
\drums {
  bd4 sn bd sn
}
````

What we'll get is this:

````xml
<DrumMode u'\\drums'>
    <MusicList u'{'>
      <Unpitched>
        <Duration u'4'>
````

What I'd expect is perhaps something like this:
````xml
<DrumMode u'\\drums'>
    <MusicList u'{'>
      <Unpitched u'bd'>
        <Duration u'4'>
      <Unpitched u'sn'>
      <Unpitched u'bd'>
      <Unpitched u'sn'>
````

**Comment by dliessi** [comment]
See also https://github.com/wbsoft/frescobaldi/issues/403:

> drum notes with implicit duration are ignored in position and length computation
> 
> Example: the length of the expression `\drummode { bd4 bd bd bd }` should be 1, but it is computed as 1/4.

**Comment by PeterBjuhr** [comment]
Great, thanks!
