### ISSUE TITLE
Fix #! line in bin/ly

### ISSUE THREAD

**Issue by dliessi** [wbsoft/python-ly#17]
* The `#!` line should contain an absolute path.
* In my opinion it is better to use `/usr/bin/env python` (or `/usr/bin/env python3`) instead of hard-coding the interpreter.

See https://github.com/wbsoft/frescobaldi/issues/640 for the reasons.

**Comment by wbsoft** [comment]
On install, the shebang line is automatically changed to point to the correct interpreter, the one that is used to run the setup.py script. So this is no problem!

**Comment by dliessi** [comment]
Yes, but if you use `ly` from the repository the shebang line is important, although I admit it is not a big deal to explicitly prepend the desired Python interpreter.
