### ISSUE TITLE
Transpose multiple files

### ISSUE THREAD

**Issue by acurl** [wbsoft/python-ly#20]
Hi!

I'd like to transpose a piece with multiple files.
The \language command is only present in one file. If I run this command:
`ly "transpose cis c" -i *ly */*ly`
The only file modified is the one that have the indication. Whereas I think all files should be modified.

**Comment by wbsoft** [comment]
I understand that one file includes the others, so that LilyPond knows the language.

So we should add a way to set the default language when reading LilyPond files. Thanks for reporting!

**Comment by acurl** [comment]
So quick!
Thanks for all your work!
