### ISSUE TITLE
Convert all relative music to absolute before entering the export process

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/python-ly#21]
Although the export functionality can handle relative input I think it would be cleaner to work with a document tree that already is in absolute mode; the relative pitches has to be converted to absolute somewhere along the process anyway. 

This also solves an issue for `\repeat unfold` expressions. The current implementation is to "unfold" these directly but that can lead to wrong octaves at the moment. The alternative is to postpone the unfolding till after the conversion to absolute pitches is made. But I think the proposed strategy is preferable.

**Comment by dliessi** [comment]
> But I think the proposed strategy is preferable.

+1
Converting relative to absolute before dealing with repeats, voices, etc. is what LilyPond actually does, if I understand correctly.

**Comment by PeterBjuhr** [comment]
Thanks!

I guess what I need to do for this to work is to create a copy of the document before the conversion to absolute mode so the actual document stays unaffected.

**Comment by wbsoft** [comment]
Indeed. The music inside a RelativeOctaveMusic expression is already in absolute pitch.

**Comment by PeterBjuhr** [comment]
I haven't closed this before because I didn't completely decide on whether to remove the old code handling relative pitches. The code isn't completely obsolete so I guess we can keep it for now...
