### ISSUE TITLE
MusicXML export crash

### ISSUE THREAD

**Issue by uliska** [wbsoft/python-ly#24]
I encounter a crash when exporting the following file to MusicXML:

```
\version "2.19.16"

% Brian Ferneyhough: La chûte d'Icare, m. 69


% First define the music, completely pure
right = {
  \tempo 8 = 56
  \time 6/8

  d''''32-> ( [ es'''
  \change Staff = "3"
  e'' c''-. ) es'''-> ( d''' ]
  \tuplet 7/4 4 {
    e''16 [ c''-. ) b'-> ( bes' a' fis'-. ) f'-> ] (
    \change Staff = "2"
    \voiceOne
    g16^ [ fis es-. ) a-> ( gis ais f-. ] )
  }
  \tuplet 3/2 {
    as32-> ( a bes ) |
  }
}


left = {
  \tuplet 18/12 {
    as,,16.-> \( a,,
    \change Staff = "2"
    f, b,-. \)
    \change Staff = "1"
    \tuplet 3/2 {
      a,,8 -> [ \( bes,, c, ]
    }
    \change Staff = "2"
    \voiceTwo
    \times 3/5 {
      fis,16-. [ \) f-> \( as, c d-. ] \)
    }
    \tuplet 6/5 {
      b,-> [ \( cis
      \change Staff = "3"
      a fis'-. \)
      \change Staff = "2"
      c->_( es] ) |
    }
  }
}

% Define score structure
\score {

  \new StaffGroup <<
    % Define four staves with "continuous" clefs
    % and keep them alive for the whole length of the score
    % (necessary because of the staff changes)
    \new Staff = "4" {
      \clef "treble^15"
      s8*6
    }
    \new Staff = "3" {
      \clef treble
      s8*6
    }
    \new Staff = "2" {
      \clef bass
      s8*6
    }
    \new Staff = "1" {
      \clef "bass_15"
      s8*6
    }

    % "put" the music in the starting staves
    \context Staff = "4" \right
    \context Staff = "1" \left
  >>
}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Global configuration
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Some global page layout settings
\paper {
  indent = 0
  ragged-last = ##f
  top-margin = 2\mm
  left-margin = 15\mm
  right-margin = 15\mm
}

% Global configuration overrides
\layout {
  \context {
    \Staff
    \accidentalStyle dodecaphonic
  }
  \context {
    \Score
    \override TupletNumber.text = #tuplet-number::calc-fraction-text
    \override TupletBracket.bracket-visibility = ##t
  }
}
```

Admittedly that's complex music, but the actual file is quite simple.
This is the error's output:

```
Traceback (most recent call last):
  File "/shared/git/foreign/frescobaldi/frescobaldi_app/file_export/__init__.py", line 64, in exportMusicXML
    writer.parse_text(doc.toPlainText())
  File "/shared/git/foreign/python-ly/ly/musicxml/lymus2musxml.py", line 93, in parse_text
    self.parse_document(doc)
  File "/shared/git/foreign/python-ly/ly/musicxml/lymus2musxml.py", line 106, in parse_document
    self.parse_tree(mustree)
  File "/shared/git/foreign/python-ly/ly/musicxml/lymus2musxml.py", line 120, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/shared/git/foreign/python-ly/ly/musicxml/lymus2musxml.py", line 132, in parse_nodes
    func_call(m)
  File "/shared/git/foreign/python-ly/ly/musicxml/lymus2musxml.py", line 532, in End
    self.mediator.change_to_tuplet(self.fraction, "stop", check_dur=False)
  File "/shared/git/foreign/python-ly/ly/musicxml/ly2xml_mediator.py", line 540, in change_to_tuplet
    tuplscaling = Fraction(tfraction[0], tfraction[1])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Commenting out the different configurations, e.g. those related to tuplets, doesn't change anything.

**Comment by PeterBjuhr** [comment]
Thanks for the full report. I'll look into this shortly!

**Comment by PeterBjuhr** [comment]
The problem was the nesting (of the tuplets).

>Admittedly that's complex music, but the actual file is quite simple.

Yes, but that is more a strength of LilyPond than anything else. Nested tuplets *is* supported in MusicXML. But even with a correct MusicXML output you'll have trouble importing it. Finale should manage though, I think.

**Comment by PeterBjuhr** [comment]
The immediate error should be fixed, I hope. But there're still some things that needs to be supported to give a correct export of the piece.

**Comment by uliska** [comment]
I can verify that the file doesn't cause a crash anymore. However, I'll try to analyze it and report export issues. I'm not sure which of those should be considered urgent, simply because the score is that complex. But probably it's a good idea to keep them reported. @PeterBjuhr maybe you can take that material and create independent issues for them as you see practical.

### Timing

The resulting file displays a 4/4 instead of a 6/8 time signature. I think this is due to an interpretation error when parsing. The `left` variable doesn't explicitly specify a `\time` command, and it seems this is exported as 4/4.  When re-importing I see that the second variable contains an explicit `\time 4/4` which seems to override the earlier 6/8 in the generated LilyPond file. I think this should be fixed.

### Score structure

There are four empty parts in the XML file because the script doesn't realize how the score is constructed, with four placeholder staves and the music placed in between. However, this is something I would happily put aside until everything else works properly. And I don't really know how that situation can be reflected in MusicXML. Maybe it's a limitation of that format, maybe not.
However, these empty parts seem to map the LilyPond expression `s8*6` for one empty 6/8 measure to six empty measures, which in turn are not re-imported at all, or rather as empty staff definitions in the score block. I think this is something that should be taken into account already now.

### Clefs

The clefs of the four systems are not properly exported, everything is reimported as regular treble clefs. I think this is because the music variables don't specify any clefs.

### Beams

Do I see it correctly that the manual beams aren't exported at all?

### Nested Tuplets

The `left` part with its nested tuplets is exported quite wrongly.
Firstly it is split into two layers, which is wrong (and presumably unnecessary).
Secondly the nesting is "merged", so a 3:2 inside 18:12 is displayed as 54:24 (or rather as "54").
The first sequence of dotted sixteenth inside the 18:12 tuplet is even displayed as regular notes with only `time-modification` used, so this is equivalent to using `\scaleDurations`.

AFAIK MusicXML *does* support nested tuplets, so we should try to fix that, maybe with simpler test cases.

### General questions

Would it be even possible to export the staff construction of this score, so that the `\new Staff` elements result in new staves but the two `\context Staff = "N"` elements do not but assign their music to the correct staff? I mean, is this supported by MusicXML?

I think it would be good to respect explicit context names. We *do* have the explicit names in the input file (`\new Staff = "1"` etc.) and it would be practical if that could be respected in the MusicXML file. It is a different story that this can't be reused for variable names upon import, though.

I have the impression that there is no way to export variables as such, preserving their name in MusicXML? I think it's a pity that the reimported music variable have completely new names.

**Comment by PeterBjuhr** [comment]
Thanks for the thorough analysis. I'll try to address everything! But first of all I'll give my own analysis in short:

1. Phrasing slurs isn't supported yet.
2. Cross-staff voicing or `\change Staff` isn't supported yet.
3. The nested tuplets still have issues.

This list isn't to be considered complete. I've been mainly focused with the nested tuplets here.

**Comment by uliska** [comment]
Is `\change Staff` even possible in MusicXML?
I have just seen some people inspecting Finale files and their MusicXML export, and if I'm not mistaken this wasn't properly exported either (maybe (but I'm not sure) the notes have even been dropped completely.

**Comment by PeterBjuhr** [comment]
If I remember it correctly you can change staff if you have several staffs in the same part.

In fact I think there already is some support for this, but only if a `GrandStaff` or `PianoStaff` is used.

I'll check and get back to this!

**Comment by PeterBjuhr** [comment]
While commenting on your analysis I think I go from the general to the more specific:

>### General questions

>Would it be even possible to export the staff construction of this score, so that the \new Staff elements result in new staves but the two \context Staff = "N" elements do not but assign their music to the correct staff? I mean, is this supported by MusicXML?

Would the previous comment about multiple staffs in the same part answer this? 

In general there are little means to retain the file structure of the ly file in the MusicXML structure as I see it.

>I think it would be good to respect explicit context names. We do have the explicit names in the input file (\new Staff = "1" etc.) and it would be practical if that could be respected in the MusicXML file. It is a different story that this can't be reused for variable names upon import, though.

I'm not sure where the context name should go to be "remembered" (any suggestion?).

The name that ends up as part name is the one set by the `Staff.instrumentName` variable.

>I have the impression that there is no way to export variables as such, preserving their name in MusicXML? I think it's a pity that the reimported music variable have completely new names.

As you know musicxml2ly creates a very standardized output, including the naming. 

Furthermore, all the variables are substituted before the parsing of the content begins (in the export) - which is very convenient. There're little ways to preserve this in the XML structure anyway.

 What I do imagine in a Frescobaldi importer is the means to create a template for the import so you have little more control over the naming and the file structure in general.

**Comment by uliska** [comment]
> While commenting on your analysis I think I go from the general to the 
> more specific:
>
>
>           General questions
>
>     Would it be even possible to export the staff construction of this
>     score, so that the \new Staff elements result in new staves but
>     the two \context Staff = "N" elements do not but assign their
>     music to the correct staff? I mean, is this supported by MusicXML?
>
> Would the previous comment about multiple staffs in the same part 
> answer this?
>

I think so.
Then I think it would be necessary to detect the situation from the 
given sample file: If there is a \context command that places the music 
in a staff then it should actually place the music in the correct staff 
in the XML file too instead of creating a new staff.
Supporting \change Staff is another thing, but in the sample file I'd 
have expected to have the music in the two initial staves.

> In general there are little means to retain the file structure of the 
> ly file in the MusicXML structure as I see it.
>
>     I think it would be good to respect explicit context names. We do
>     have the explicit names in the input file (\new Staff = "1" etc.)
>     and it would be practical if that could be respected in the
>     MusicXML file. It is a different story that this can't be reused
>     for variable names upon import, though.
>
> I'm not sure where the context name should go to be "remembered" (any 
> suggestion?).
>
> The name that ends up as part name is the one set by the 
> |Staff.instrumentName| variable.
>

So, the P1, P2... are fixed rules by MusicXML?
I don't know enough about the MusicXML specifications, but I would find 
it logical to have <part 
id="lilypond-staff-name"><part-name>Staff.instrumentName...

>     I have the impression that there is no way to export variables as
>     such, preserving their name in MusicXML? I think it's a pity that
>     the reimported music variable have completely new names.
>
> As you know musicxml2ly creates a very standardized output, including 
> the naming.
>
> Furthermore, all the variables are substituted before the parsing of 
> the content begins (in the export) - which is very convenient. 
> There're little ways to preserve this in the XML structure anyway.
>

OK, I see.

> What I do imagine in a Frescobaldi importer is the means to create a 
> template for the import so you have little more control over the 
> naming and the file structure in general.
>
Sounds reasonable

**Comment by PeterBjuhr** [comment]
>>>I think it would be good to respect explicit context names. We do
     have the explicit names in the input file (\new Staff = "1" etc.)
     and it would be practical if that could be respected in the
     MusicXML file. It is a different story that this can't be reused
     for variable names upon import, though.

>> I'm not sure where the context name should go to be "remembered" (any
 suggestion?).

> The name that ends up as part name is the one set by the
 |Staff.instrumentName| variable.
So, the P1, P2... are fixed rules by MusicXML?
I don't know enough about the MusicXML specifications, but I would find
it logical to have <part
id="lilypond-staff-name"><part-name>Staff.instrumentName...

Maybe not, I haven't really thought about it before! In general I think this a good question! But I can't see the use at the moment of storing the staff name in this way. Furthermore even if a different naming of the part id is allowed - which sounds reasonable - maybe the P1, P2 ... convention is *expected* in some cases.

**Comment by uliska** [comment]
Well, deviating from conventions should only be done for very good reasons ...

**Comment by PeterBjuhr** [comment]
Exactly :)

**Comment by PeterBjuhr** [comment]
>### Score structure

>There are four empty parts in the XML file because the script doesn't realize how the score is constructed, with four placeholder staves and the music placed in between. 

I've created an issue for this, see #26 

>However, these empty parts seem to map the LilyPond expression s8*6 for one empty 6/8 measure to six empty measures, which in turn are not re-imported at all, or rather as empty staff definitions in the score block.

Do you mean that 6 empty measures are created in each part? That is not what I have...

**Comment by uliska** [comment]
When re-importing there are just empty staff definitions for these four parts, but in the exported XML file the four parts start with something like
```
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>120960</divisions>
        <time symbol="common">
          <beats>4</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
      </attributes>
      <forward>
        <duration>60480</duration>
      </forward>
    </measure>
    <measure number="2">
      <forward>
        <duration>60480</duration>
      </forward>
    </measure>
```
where measures 3-6 are identical to 2.

I can only imagine that `s8*6` is causing this.

**Comment by PeterBjuhr** [comment]
Sorry, now when I redo the import I see it!

Strange that I didn't have that in the older version of the XML file...

I'll look into it, and create a new issue if relevant!

**Comment by PeterBjuhr** [comment]
>>So, the P1, P2... are fixed rules by MusicXML?
I don't know enough about the MusicXML specifications, but I would find
it logical to have id="lilypond-staff-name">Staff.instrumentName...

>Maybe not, I haven't really thought about it before! In general I think this a good question! But I can't see the use at the moment of storing the staff name in this way. Furthermore even if a different naming of the part id is allowed - which sounds reasonable - maybe the P1, P2 ... convention is expected in some cases.

We now store the context id. I can also confirm that the P1, P2 ... naming *is* just a convention. So in the future if we see it useful we could use the context id as part id also in the final XML file.
