### ISSUE TITLE
Better check if Staff already exists (for contexts)

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/python-ly#26]
The check if a Staff already exists needs to be better!

Currently it can handle this scenario:

````lilypond
\score {
  \new StaffGroup <<

    \new Staff = "1" {
      \clef treble
      \context Staff = "1" { c'1 }
    }
    \new Staff = "2" {
      \clef bass
      \context Staff = "2" { c1 }
    }
  >>
}
````

But not this:

````lilypond
\score {
  \new StaffGroup <<

    \new Staff = "1" {
      \clef treble
      s1
    }
    \new Staff = "2" {
      \clef bass
      s1
    }
    \context Staff = "1" { c'1 } 
    \context Staff = "2" { c1 }
  >>
}
````

In the later case four parts are created instead of two.

**Comment by uliska** [comment]
Just to remark: This is "hopefully" closed by that commit. I'll test it.

**Comment by uliska** [comment]
I can confirm that *this* issue is fixed now.

**Comment by PeterBjuhr** [comment]
Thanks!

**Comment by PeterBjuhr** [comment]
There are still some issues in this area. But as the issue is labelled I consider this closed...
