### ISSUE TITLE
Implicit time signatures are exported as explicit

### ISSUE THREAD

**Issue by uliska** [wbsoft/python-ly#29]
When no time signature is specified in LilyPond music (because it can be inferred from the context) an explicit 4/4 time signature is exported (because that's considered LilyPond's default, I assume).

So, when exporting this file:

```lilypond
\score {
  <<
    \new Staff {
      \time 6/8
      c'8 c' c' c' c' c'
    }
    \new Staff {
      \clef bass
      c8 c8 c8 c8 c8 c8
    }
  >>
}
```
`P2` will have an explicit 4/4 time signature. When re-importing that to LilyPond the second one will override the first one so the piece is (wrongly) engraved as 4/4

**Comment by PeterBjuhr** [comment]
I don't think MusicXML allows implicit time signatures even if musicxml2ly perhaps does. So the solution as I see it is to not use the default 4/4 but instead the explicit 6/8 from the other staff.

**Comment by uliska** [comment]
Seems to me the right solution.
However, this means we have to actually understand what the current time 
signature is.
Which might be complicated because you could for example reuse a music 
variable in different places with different time signatures.

**Comment by PeterBjuhr** [comment]
Luckily variables are substituted before the export begins. That said, I agree with you that it is complicated at least when the time signatures are changing. I think the time signatures have to be saved separately and then merged to each part where they aren't explicit set.

Anybody know how LilyPond handles this?

**Comment by uliska** [comment]
basically I'd say by having the timing information handled by the Score 
context and not by Staff or Voice.

**Comment by wbsoft** [comment]
Normally LilyPond handles the timing information at the Score level. But when that is moved to the staff level, things are handled different. See e.g. the second example (Different time signatures with unequal-length measures) at http://www.lilypond.org/doc/v2.18/Documentation/notation/displaying-rhythms#polymetric-notation

**Comment by PeterBjuhr** [comment]
The example is interesting! Now we export this as different time signatures (with unequal length measures) - with or without the overhead of removing the `Timing_translator` and the `Default_bar_line_engraver` needed by LilyPond.

I don't know if this is allowed by MusicXML or not. But it may be hard to get an importer to import this correctly.

**Comment by uliska** [comment]
Well, you'll have a hard time finding a program that can actually *display* that correctly ;-)
SCORE surely can do that (because it doesn't have any notion about timing at all), but FInale or Sibelius can't handle that, and you'll have to do dirty tricks to make that happen. I'd like to see the MusicXML export from *their* side ...

**Comment by PeterBjuhr** [comment]
Maybe we would have come far with just keeping the implicit time signatures implicit. But I see a connection to #27 and #32 - it would have been good to know the time signature and the bar length in each measure. Then we could:

1. Make implicit time signatures explicit #29
2. Correctly split a large rest (e. g. `s4*12`) into different bars #27 
3. Overall insert bar splits without the guide of barchecks #32
