### ISSUE TITLE
Properly export clefs to MusicXML

### ISSUE THREAD

**Issue by uliska** [wbsoft/python-ly#33]
When exporting to MusicXML not all clefs are supported.
[This LilyPond file](https://gist.github.com/uliska/3e9647cd4be50550ca36) lists all clef styles as per LilyPond 2.19.21. When exporting this file some clefs are not exported to MusicXML

```
GG
tenorG
varC
altovarC
tenorvarC
baritonevarC
baritonevarF
subbass
```

Also (and this makes it relate to the Ferneyhogh example) clefs with `^15` or `_15` modifiers are not exported at all. However, if I manually add a clef with `<clef-octave-change>-2</clef-octave-change>` to the MusicXML it will be correctly re-imported. So there's no limitation on the MusicXML side involved.

---

And generally I'd like to ask if there's a way to export the actual clef names instead of only the shape and position. The current solution reduces the semantic information.

**Comment by PeterBjuhr** [comment]
As far as I know the clefs are represented in the MusicXML as shape (clef type) + position (and the optional octave change).

See [`clefname2clef`] (https://github.com/wbsoft/python-ly/blob/master/ly/musicxml/ly2xml_mediator.py#L854 for the current support) for the current support.

**Comment by uliska** [comment]
See also http://forums.makemusic.com/viewtopic.php?f=12&t=2953&p=8941#p8941
