### ISSUE TITLE
Rhythm -> Make explicit gives wrong LilyPond code on 16+~

### ISSUE THREAD

**Issue by dliessi** [wbsoft/python-ly#35]
In Frescobaldi Tools -> Rhythm -> Make explicit on `c16 c~` gives `c16 c~16` instead of `c16 c16~`.

Frescobaldi: 2.18.1, python-ly: 0.9.2

**Comment by wbsoft** [comment]
this is introduced in 7d86539f4e45db8566970ef28eb4d4140e1cb3d8

**Comment by dliessi** [comment]
The problem still exists in latest master branch.

(See also #36.)

**Comment by wbsoft** [comment]
are you sure you are using the correct ly module? The text
```lilypond
{ c16 c~ }
```
is after *Tools→Rhythm→Make explicit* correctly changed to:
```lilypond
{ c16 c16~ }
```

**Comment by PeterBjuhr** [comment]
I can confirm that it works.

My test case:

```lilypond
{
  c4. c16 c~ c4 c 
}
````

gives:

```lilypond
{
  c4. c16 c16~ c4 c4 
}
````

**Comment by dliessi** [comment]
Yes, indeed it works.
It was a mistake in PYTHONPATH precedence on my side.
Sorry for the noise. :)
