### ISSUE TITLE
Option to simplify spelling when transposing pitches

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/python-ly#40]
This is somewhat related to the inversions in #39 but it can be explained as an independent issue/question:

Let's say we have:

````lilypond
es d e gis
````

And we transpose that *es -> e*:

````lilypond
e dis eis gisis
````

But to simplify spelling we may instead want:

````lilypond
e dis f a
````

The Python-ly/Frescobaldi transposer of course mimics the `\transpose` command in LilyPond which will give the same result as the second example. But in other notation programs there are often an option to simplify spelling at least to avoid double sharps and flats.

Is this something to consider?

**Comment by wbsoft** [comment]
I think this should become a separate command, let's call it simplify_accendentals. Indeed it should be implemented as a transposer.

**Comment by wbsoft** [comment]
See ceddb9d
