### ISSUE TITLE
Newbie HowTo question (using ly to colorize code)

### ISSUE THREAD

**Issue by uliska** [wbsoft/python-ly#41]
I feel quite stupid writing this, but I got stuck right at the start :-(

I want to write a small script that takes a string from a file or as a command line argument and that returns/prints colorized HTML.

When looking through the docs and source code it seems I need HtmlWriter.html() for what I want, but I have to provide it a QTextCursor, which itself needs a QTextDocument.

However, when I try to set this up like

```python
from ly.colorize import HtmlWriter
from PyQt4 import QtGui
doc = QtGui.QTextDocument('\\version "2.19.22" \n#(define a b)')
cursor = QtGui.QTextCursor(doc)
writer = HtmlWriter()
print writer.html(cursor)
```

the script fails with

```
Traceback (most recent call last):
  File "./colorize-lilypond", line 15, in <module>
    print writer.html(cursor)
  File "/shared/git/foreign/python-ly/ly/colorize.py", line 561, in html
    body = html(cursor, self.css_mapper or css_mapper(), formatter)
  File "/shared/git/foreign/python-ly/ly/colorize.py", line 423, in html
    for t, style in melt_mapped_tokens(map_tokens(cursor, mapper)):
  File "/shared/git/foreign/python-ly/ly/colorize.py", line 289, in melt_mapped_tokens
    for t, s in mapped_tokens:
  File "/shared/git/foreign/python-ly/ly/colorize.py", line 272, in map_tokens
    text = cursor.document.plaintext()
```

Sorry for the stupid question, but what do I have to do to pass a string into a script and print/return the colored HTML from it?

**Comment by PeterBjuhr** [comment]
I have no experience with that module and I can't help out from later tonight. But shouldn't it be a `ly.document.Cursor`?

**Comment by uliska** [comment]
Thanks for the pointer!

```python
from ly.colorize import HtmlWriter
import ly.document
from PyQt4 import QtGui
doc = ly.document.Document('\\version "2.19.22" \n#(define a b)')
cursor = ly.document.Cursor(doc)
writer = HtmlWriter()
print writer.html(cursor)
```
Does what I expect now. I think I'll manage the fine-tuning now :-)

**Comment by wbsoft** [comment]
It might be confusing, but it is good to realize that `ly` knows nothing about `Qt`.

So although Frescobaldi uses `QTextDocument` as the base for its document instances, all interacting with `ly` occurs through `ly.document`, which is inherited by Frescobaldi's `lydocument.Document`.

When any `ly` function is called from Frescobaldi, a `frescobaldi_app.lydocument.Document` is instantiated (which happens very quick, as the syntax highlighter on the QTextDocument already has performed the parsing). And then the `ly` function operates on that Document (which dispatches the changes back to the QTextDocument)`.

When you only want to interact with `ly`, there is no need to import `PyQt4`.

So:
```python
import ly.document
import ly.colorize
doc = ly.document.Document('\\version "2.19.22" \n#(define a b)')
cursor = ly.document.Cursor(doc)
writer = ly.colorize.HtmlWriter()
print writer.html(cursor)
```
will suffice :-)

**Comment by uliska** [comment]
Thanks. I've found this out when the script failed on my server.

By now everything works, I have python-ly up and running, calling a script from the git hook, so whenever my GitBook is pushed to the remote repository, the LilyPond code examples are parsed and colorized, as you can see for example on http://bookbranches.openlilylib.org/scheme-tutorials/lilypond/extending/scheme/03.html.
Other than on the blog the examples are not stored as colorized HTML in the files but as plain text Lily code wrapped in a `{% lilypond %}{% endlilypond %}` block.

Absolutely awesome :-)

**Comment by wbsoft** [comment]
Great! `python-ly` is quite cool, it only uses python and depends on nothing else !
