### ISSUE TITLE
musicxml export of \relative {} one octave too high

### ISSUE THREAD

**Issue by mtarenskeen** [wbsoft/python-ly#46]
If I try to convert the following snippet, using ly, to MusicXML

>\relative {c' d e f}

the result is one octave too high.
The old syntax

>\relative c' {c d e f}

is converted correctly.

**Comment by wbsoft** [comment]
This is because of a change in LilyPond. Beforehand, it used to use c' as the default first pitch. 

But since 2.18 when no starting pitch is given, the first pitch is taken as an absolute pitch. Which is the same as effectively using f as starting pitch. 

So we should find a way to tell python-ly how to interpret relative music without starting pitch.

**Comment by mtarenskeen** [comment]
I see. Then python-ly should check for a \version line? Or require lilypond 2.18 or higher? I am in favour of the last option. Python-ly should not have to duplicate the complete functionality of the convert-ly script. People should run convert-ly before using python-ly if needed.
I don't think there are many pre-2.18 Lilypond files that use \relative without a starting pitch. So I think it is quite, but not completely, safe to assume that if \relative is used without a starting pitch the 2.18+ behaviour should be used: The first pitch is an absolute pitch. The latest stable python-ly releases should be based on the latest stable lilypond version.

**Comment by PeterBjuhr** [comment]
There actually is an closed issue about this - #18. @mtarenskeen  what version of the code are you running?

**Comment by mtarenskeen** [comment]
I was using today's python-ly 0.9.3 from Git

**Comment by PeterBjuhr** [comment]
I see, thanks! Then it seems we have a regression. I'll take a look!

**Comment by mtarenskeen** [comment]
could it be related to closed issue #21 ?

**Comment by PeterBjuhr** [comment]
Yes, exactly what I also thought!

**Comment by wbsoft** [comment]
@PeterBjuhr are you converting to absolute first? Then you are using the routines in ly.pitch.rel2abs.py. There is code that reads a relative expression. At line 109 it picks c1 as default. I propose that I change that code, and add an argument to `rel2abs()`, to make it possible that f0 is take instead as default pitch (effectively taking the first pitch as absolute).

**Comment by wbsoft** [comment]
Python-ly should not check the version line, it should simply be able to perform the desired operation correcly. Frescobaldi otoh *should* check the version line to perform the correct operation by default. But evenso we might need to make \relative behaviour configurable in Frescobaldi. For example when converting absolute to relative, it should be configurable whether or not to use a starting pitch, and which one would be implied. But that's another issue: wbsoft/frescobaldi#766.

**Comment by PeterBjuhr** [comment]
>@PeterBjuhr are you converting to absolute first? Then you are using the routines in ly.pitch.rel2abs.py. There is code that reads a relative expression. At line 109 it picks c1 as default. I propose that I change that code, and add an argument to rel2abs(), to make it possible that f0 is take instead as default pitch (effectively taking the first pitch as absolute).

That sounds great!

**Comment by wbsoft** [comment]
Ok, I will do!
