### ISSUE TITLE
barchecklines | are not real barlines

### ISSUE THREAD

**Issue by mtarenskeen** [wbsoft/python-ly#47]
It looks like python-ly is interpreting barchecklines | as if they are real
barlines. In LilyPond this isn't true, it's just a tool to check your
lilypond sourcecode, and you can leave it out. Even if that's not
recommended practice. Consider the following example:

>\version "2.19.28"
>\score {
>  \new Staff {
>    \time 4/4
>    \relative c' {
>      c4 d e f g a b c |
>      c b a g | f e d c
>    }
> }
>  \layout {}
>}

When compiled using LilyPond this gives no errors, no warnings, and correct
pdf output with 4 bars, separated by 3 barlines. When using "ly musicxml -o
barchecklines.xml barchecklines.ly", if I import and view the MusicXML file
using MuseScore the first barline is missing.

![barchecklines](https://cloud.githubusercontent.com/assets/3509304/10165760/3061e72c-66c1-11e5-86bb-aa9219aa6caf.png)

**Comment by PeterBjuhr** [comment]
It's a documented limitation of the export function that it needs explicit barchecks to be able to separate measures. Of course this is not consistent with how LilyPond compiles the code, and it is on the todo-list to improve this. 

As we already have an open issue describing this (#32), I close this.

**Comment by mtarenskeen** [comment]
ok.
