### ISSUE TITLE
LyricsTo.ly() calls object.ly(), will fail

### ISSUE THREAD

**Issue by proski** [wbsoft/python-ly#5]
Method `ly` in `class LyricsTo` in `dom.py` calls

    super(Named, self).ly(printer)

The superclass of `Named` is `object`, which has no method called `ly`, so it will fail.

The convention is to call only methods of the immediate superclass:

    super(LyricsTo, self).ly(printer)

That would be dispatched to `class Enclosed`

**Comment by wbsoft** [comment]
I think because `Named` is mentioned before `Enclosed` in [StatementEnclosed](https://github.com/wbsoft/python-ly/blob/master/ly/dom.py#L502) it is also dispatched to `Enclosed`:
```
>>> import ly.dom
>>> d=ly.dom.Document()
>>> ly.dom.LyricsTo('bla', d)
<ly.dom.LyricsTo object at 0xb5199fcc>
>>> d
<ly.dom.Document object at 0xb7045784>
>>> print d.ly(ly.dom.Printer())
\lyricsto "bla" { }

```
(There are some places where multiple inheritance is used in `ly.dom`.)

**Comment by proski** [comment]
I see. Let me try to actually trigger that code.

**Comment by proski** [comment]
Indeed, super(Name, self) was redirected to class Enclosed, which was the next in line after Named for LyricsTo ancestors.

super() is meant to access the immediate parent only. super(LyricsTo)ly() would call Name.ly() on top of Enclosed.ly(), which would give a wrong result. That's why calling Enclosed.ly() was needed.

I've made it explicit in 3b35ef3914c1026a778ef52cdd7edbea05b6f6df
