### ISSUE TITLE
musicxml export fails to handle non-absolute \include files

### ISSUE THREAD

**Issue by rshura** [wbsoft/python-ly#59]
When the lilypond file has **\include "name"** directive, it is handled correctly by musicxml export **only** if the name is absolute.  The code seems to be written to attempt to also resolve relative names (assuming that the includee is in same directory as the includer file), but it does not work with musicxml.

$ ly --version
ly 0.9.3

Details:
* the **music.items.Document** class does contain the **resolve_filename** method that looks good;
* however, the **run** method of the **cli.command.musicxml** class only passes **cursor.document.plaintext()** to the parser, so the document in question has filename which is None.

I didn't go too deep into this, but I could not immediately see a quick fix, hence no patch yet.  Maybe the the **run** method of the **cli.command.musicxml** class should call **writer.parse_document(cursor.document)** instead of **writer.parse_text(cursor.document.plaintext())**?

Please let me know if you want my help on this.  Thanks!

**Comment by rshura** [comment]
That worked, thanks!

**Comment by wbsoft** [comment]
Great, thanks for reporting and testing!! And great that you looked so far into the code :-)
