### ISSUE TITLE
Ottava xml export may use uninitialized data

### ISSUE THREAD

**Issue by proski** [wbsoft/python-ly#6]
The implempenation of ottava export to MusicXML (new_ottava in ly2xml_mediator.py) has two problems.

If the ottava argument is 0, self.oct_size and self.oct_plac are used, but they can only be initialized by a previous ottava witg a non-zero argument. Thus "\ottava #0" in the beginning of the voice leads to an exception.

Also, self.oct_size and self.oct_plac are not changed for "\ottava #0", so all subsequent occurrences of "\ottava #0" keep writing them to the output file. Example:

    \version "2.18.2"
    {
      c''1
      \ottava #0
      c''
      \ottava #0
      c''
      \ottava #1
      c''
      \ottava #0
      c''
      \ottava #0
      c''
    }

    $ python2 ly musicxml -o ottava1.xml ottava1.ly
    Warning: SchemeItem not implemented!
    Mediator instance has no attribute 'oct_size'
    Warning: SchemeItem not implemented!
    Mediator instance has no attribute 'oct_size'
    $ grep octave-shift ottava1.xml
              <octave-shift size="8" type="down" />
              <octave-shift size="8" type="stop" />
              <octave-shift size="8" type="stop" />

**Comment by PeterBjuhr** [comment]
Yes, it seems like I expected LilyPond code which makes sense musically. But as your example is handled by LilyPond it should also be anticipated by the exporter. I'll improve this! Thank's for reporting!

**Comment by proski** [comment]
Thank you. I've made futher improvements on top of it to fix all pylint warnings in the function.

**Comment by PeterBjuhr** [comment]
Thanks for the review!
