### ISSUE TITLE
Let the transpose update octave checks

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/python-ly#68]
see wbsoft/frescobaldi#782

**Comment by wbsoft** [comment]
@sincere-music  Please provide an example that is incorrectly transposed.

Currently, I don't see a bug. When transposing
```lilypond
\relative c' {
  c d e f=' g
  \octaveCheck c''
  g2
}
```
from c to g, this is the (correct) result:
```lilypond
\relative c'' {
  g a b c='' d
  \octaveCheck g''
  d2
}
```

**Comment by sincere-music** [comment]
On 20.04.2016 00:50, Wilbert Berendsen wrote:
>
> Closed #68 <https://github.com/wbsoft/python-ly/issues/68>.
>

Now I remember: The shorthand is the problem. Transposing

\relative {
   c'='
}

from c to b,

gives

\relative {
   b'='
}

which is wrong.

**Comment by wbsoft** [comment]
This is not a bug: It is because `ly` understands `\relative` without startpitch still the LilyPond <= 2.16 way, i.e. the startpitch  `c'` is assumed.

Since LilyPond 2.18 the meaning of `\relative { ... }` has changed: when no startpitch is given, the first note is assumed to be absolute (which is equivalent to assuming `f` as startpitch).

`python-ly` 0.9.4 is able to understand `\relative` without startpitch both ways. If you are using the command line interface, you can set the variable `rel-absolute` to `true`. When using the python library, you can use the `first_pitch_absolute` argument of the `ly.pitch.transpose.transpose` function.

**Comment by wbsoft** [comment]
In Frescobaldi this is handled transparently: Frescobaldi looks at the version of the docuent and chooses the correct meaning :-)

**Comment by sincere-music** [comment]
I should have avoided dragging in \relative. The same problem occurs with:

{ c'=' }

By transposing from c to b, I get

{ b=' }

which, again, is wrong, i.e. b' will be printed and a warning output.

**Comment by wbsoft** [comment]
I think LilyPond ignores octave checks in non-relative music . Although they do not produce syntax errors, they are not meant to be used outside `\relative`. Indeed python-ly leaves them simply alone.

I don't get warnings from LilyPond.
