### ISSUE TITLE
new_tempo() in ly2xml_mediator.py uses duration_from_tokens() incorrectly

### ISSUE THREAD

**Issue by proski** [wbsoft/python-ly#7]
duration_from_tokens() returns a tuple with two values. new_tempo() expects three values. The log shows that duration_from_tokens() used to return three values. It was changed in ed7e3364 to return two values. check_duration() was updated, but new_tempo() wasn't.

**Comment by PeterBjuhr** [comment]
Thanks for spotting that! I'll look into it shortly.

**Comment by proski** [comment]
Thank you, Peter! I'm glad I didn't try to fix it myself. I would never be able to write that! Pylint is actually finding interesting stuff now.

**Comment by PeterBjuhr** [comment]
Thanks! Yes, it turned out to be a somewhat larger issue. Please let me know what you (and Pylint) find... :)
